config/routes.rb
Rails.application.routes.draw do
  resources :plates
  resources :clients 

  root 'clients#new'

end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :plates
end

app/models/plate.rb
class Plate < ActiveRecord::Base
	validates :order_number, presence: true
	belongs_to :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  def create
    @client = Client.new(client_params)
    @client.status = false
    @client.price = 0
    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :email, :card_number, :order_number, :status, :price)
    end
end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController
  before_action :set_plate, only: [:show, :edit, :update, :destroy]

  # GET /plates
  # GET /plates.json
  def index
    @plates = Plate.all
  end

  # GET /plates/1
  # GET /plates/1.json
  def show
  end

  # GET /plates/new
  def new
    @plate = Plate.new
  end

  # GET /plates/1/edit
  def edit
  end

  # POST /plates
  # POST /plates.json
  def create
    @plate = Plate.new(plate_params)

    respond_to do |format|
      if @plate.save
        format.html { redirect_to @plate, notice: 'Plate was successfully created.' }
        format.json { render :show, status: :created, location: @plate }
      else
        format.html { render :new }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end

    Client.all.each do |c|
      byebug
      if c.order_number == @plate.order_number
        c.price = c.price + 45 * @plate.peso
        c.save
      end
    end
  end

  # PATCH/PUT /plates/1
  # PATCH/PUT /plates/1.json
  def update
    respond_to do |format|
      if @plate.update(plate_params)
        format.html { redirect_to @plate, notice: 'Plate was successfully updated.' }
        format.json { render :show, status: :ok, location: @plate }
      else
        format.html { render :edit }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plates/1
  # DELETE /plates/1.json
  def destroy
    @plate.destroy
    respond_to do |format|
      format.html { redirect_to plates_url, notice: 'Plate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plate
      @plate = Plate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plate_params
      params.require(:plate).permit(:peso, :order_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/plates_helper.rb
module PlatesHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :card_number %><br>
    <%= f.text_field :card_number %>
  </div>
  <div class="field">
    <%= f.label :order_number %><br>
    <%= f.text_field :order_number %>
  </div>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Card number</th>
      <th>Order number</th>
      <th>Status</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.email %></td>
        <td><%= client.card_number %></td>
        <td><%= client.order_number %></td>
        <td><%= client.status %></td>
        <td><%= client.price %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>
<br>
<%= link_to 'Have a plate', new_plate_path %>
<br>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Card number:</strong>
  <%= @client.card_number %>
</p>

<p>
  <strong>Order number:</strong>
  <%= @client.order_number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @client.status %>
</p>

<p>
  <strong>Price:</strong>
  <%= @client.price %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VitorTp3P2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plates/_form.html.erb
<%= form_for(@plate) do |f| %>
  <% if @plate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plate.errors.count, "error") %> prohibited this plate from being saved:</h2>

      <ul>
      <% @plate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'peso (kg)' %><br>
    <%= f.text_field :peso %>
  </div>
  <div class="field">
    <%= f.label :order_number %><br>
    <%= f.text_field :order_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plates/edit.html.erb
<h1>Editing Plate</h1>

<%= render 'form' %>

<%= link_to 'Show', @plate %> |
<%= link_to 'Back', plates_path %>

app/views/plates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Plates</h1>

<table>
  <thead>
    <tr>
      <th>Peso</th>
      <th>Order number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plates.each do |plate| %>
      <tr>
        <td><%= plate.peso %></td>
        <td><%= plate.order_number %></td>
        <td><%= link_to 'Show', plate %></td>
        <td><%= link_to 'Edit', edit_plate_path(plate) %></td>
        <td><%= link_to 'Destroy', plate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plate', new_plate_path %>

app/views/plates/new.html.erb
<h1>New Plate</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/plates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Peso:</strong>
  <%= @plate.peso %>
</p>

<p>
  <strong>Order number:</strong>
  <%= @plate.order_number %>
</p>

<%= link_to 'Edit', edit_plate_path(@plate) %> |
<%= link_to 'Back', clients_path %>